import js from '@eslint/js';
import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import reactHooks from 'eslint-plugin-react-hooks';
import solid from 'eslint-plugin-solid';

/**
 * Flat config for the whole workspace.
 *
 * Formatting is Prettier's job (`.prettierrc`) — nothing here duplicates it, so
 * there are no stylistic rules. What is left is correctness and dead code.
 *
 * Type-aware linting is deliberately not enabled. It needs a `project` per
 * package and is substantially slower, and `tsc` already runs over both `src`
 * and `tests` in CI via each package's `tsconfig.tests.json`. Turn it on only
 * for a specific rule that earns the cost.
 *
 * Rules are chosen, not inherited wholesale — see the notes on each block.
 */

/** Globals for the handful of plain-JS files: build scripts and configs. */
const nodeGlobals = {
  console: 'readonly',
  process: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  Buffer: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  fetch: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  queueMicrotask: 'readonly',
  structuredClone: 'readonly',
  AbortController: 'readonly',
};

export default [
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/.turbo/**',
      '**/test-results/**',
      '**/playwright-report/**',
      'apps/docs/.astro/**',
      // Generated by TypeDoc on every docs build; gitignored.
      'apps/docs/src/content/docs/api/reference/**',
    ],
    // Not ignored so much as unreachable: `.astro` (5 files) and `.mdx` (20)
    // need eslint-plugin-astro / @eslint/markdown to parse. Deliberately out of
    // scope for now — adding a parser is its own decision, not a side effect of
    // turning lint on.
  },

  js.configs.recommended,

  // Plain JS: build scripts, this config, astro config.
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: nodeGlobals,
    },
  },

  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsParser,
      parserOptions: { ecmaVersion: 'latest', sourceType: 'module' },
    },
    plugins: { '@typescript-eslint': tsPlugin },
    rules: {
      ...tsPlugin.configs.recommended.rules,

      // `no-undef` is redundant under TypeScript and actively wrong here: it
      // has no view of the DOM lib, so it flags PointerEvent, HTMLElement,
      // document, window and friends — 459 false positives across this repo,
      // 92% of every finding before it was turned off. typescript-eslint
      // documents disabling it; `tsc` is the authority on undefined names.
      'no-undef': 'off',

      // Defer to the TS-aware version, and honour the leading-underscore
      // convention the codebase already uses for deliberately-unused names.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          // `^_` is the codebase's existing convention for deliberately-unused
          // names. `Brand$` exempts the branded-id idiom CLAUDE.md mandates:
          //   declare const imageIdBrand: unique symbol;
          //   export type ImageId = string & { readonly __brand: typeof imageIdBrand };
          // The const is genuinely used, but only in a type position, which
          // this rule reports as unused.
          varsIgnorePattern: '^_|Brand$',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },

  // React. Only the two classic rules. `exhaustive-deps` is what the
  // `eslint-disable` comments already in `@osdlabel/react` refer to, so
  // enabling it makes that existing reasoning load-bearing again rather than
  // silently unenforced. v7's compiler-era rules (`refs`, `immutability`,
  // `set-state-in-effect`) are deliberately NOT enabled: they contradict the
  // ref patterns CLAUDE.md prescribes for holding mutable values across
  // renders for OSD handlers, and would flag ~23 intentional usages.
  {
    files: ['packages/react/src/**/*.{ts,tsx}', 'apps/dev-react/src/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/exhaustive-deps': 'error',
      'react-hooks/rules-of-hooks': 'error',
    },
  },

  // Solid. `no-destructure` enforces a rule CLAUDE.md already states in prose
  // ("Do not destructure props — it breaks reactivity"). `reactivity` catches
  // the mistake class CLAUDE.md warns about most, but is noisy enough to be a
  // warning rather than an error: CI does not fail on it, so the current 27
  // (18 in packages/solid, 9 in apps/docs) can be triaged deliberately instead
  // of in one batch.
  {
    files: [
      'packages/solid/src/**/*.{ts,tsx}',
      'apps/dev/src/**/*.{ts,tsx}',
      // apps/docs' demo components are Solid too — five of them import from
      // solid-js, so they belong under the same rules.
      'apps/docs/src/**/*.{ts,tsx}',
    ],
    plugins: { solid },
    rules: {
      'solid/no-destructure': 'error',
      'solid/reactivity': 'warn',

      // Solid assigns refs through the `ref={el}` binding, which its JSX
      // transform turns into an assignment ESLint cannot see. Forcing the rule
      // on across all three trees below yields exactly one finding —
      // `ViewerCell.tsx:37` — and it is the legitimate idiom, so this hides
      // nothing else. Note the disable covers the whole block (solid, dev and
      // docs), not just `@osdlabel/solid`.
      'no-unassigned-vars': 'off',
    },
  },
];
